### ISSUE TITLE
Electron 한국어 문서 번역 현황

### ISSUE THREAD

**Issue by preco21** [preco21/electron#5]
> 🌍 ;ㅅ; 데굴데굴..

모든 문서의 번역은 `master` 브랜치가 아닌 `korean-docs-#` 브랜치에서 진행됩니다.
## 미 번역 문서
- [x]  [`development/debug-instructions-macos.md`](https://github.com/preco21/electron/blob/korean-docs-11/docs-translations/ko-KR/development/debug-instructions-macos.md)
- [x] [`tutorial/offscreen-rendering.md`](https://github.com/preco21/electron/blob/korean-docs-11/docs-translations/ko-KR/tutorial/offscreen-rendering.md)
- [x] [`tutorial/about.md`](https://github.com/preco21/electron/blob/korean-docs-11/docs-translations/ko-KR/tutorial/about.md)
- [x] [`tutorial/accessibility.md`](https://github.com/preco21/electron/blob/korean-docs-11/docs-translations/ko-KR/tutorial/accessibility.md)
- [x] [`api/web-contents.md`](https://github.com/preco21/electron/blob/korean-docs-11/docs-translations/ko-KR/api/web-contents.md) (Outdated)
- [x] [`styleguide.md`](https://github.com/preco21/electron/blob/korean-docs-11/docs-translations/ko-KR/styleguide.md) (Outdated)
## 미 반영 변경 커밋
- [x] https://github.com/electron/electron/commit/06a354a2eb5334840894f2865c8237956e38e9c9
- [x] https://github.com/electron/electron/commit/36a0a491c9b1fbf59112f8aa1bad4fce8a82b881
- [x] https://github.com/electron/electron/commit/9eacd07eda28147d09219bb8d16484a3a8e14e61
- [x] https://github.com/electron/electron/commit/2b0cd97bb8c84c696a86717eddc443ca630c4d25
- [x] https://github.com/electron/electron/commit/6cc68638e76d23d499cc1a07a2f343da8e22cc8f
## 미 반영 변경 사항
- [x] [Compare Changes](https://github.com/electron/electron/compare/38cc56efee6d3ba6a685c3a698b7bf7589d42420...7ff56499657c91306fc42a71d4ca63b2dadc0f08)

**Comment by preco21** [comment]
https://github.com/electron/electron/compare/38cc56efee6d3ba6a685c3a698b7bf7589d42420...7ff56499657c91306fc42a71d4ca63b2dadc0f08 미 반영 문서 8/27일 분까지 번역 완료되었으나 중간 중간 미 반영 문서의 커밋이 충돌되어 문제를 겪고 있습니다:
- [x] https://github.com/electron/electron/compare/electron:38cc56efee6d3ba6a685c3a698b7bf7589d42420...7ff56499657c91306fc42a71d4ca63b2dadc0f08#diff-ce0f5822b4e86e66dd7c08335ff3ee96R50
- [x] https://github.com/electron/electron/compare/electron:38cc56efee6d3ba6a685c3a698b7bf7589d42420...7ff56499657c91306fc42a71d4ca63b2dadc0f08#diff-9b078be8f43e00e3b99edb5be31fa353L1164
- [x] https://github.com/electron/electron/compare/electron:38cc56efee6d3ba6a685c3a698b7bf7589d42420...7ff56499657c91306fc42a71d4ca63b2dadc0f08#diff-9b078be8f43e00e3b99edb5be31fa353R42

위 문서는 미 반영 커밋이 모두 번역되어야 적용할 수 있는 부분입니다.

**Comment by preco21** [comment]
1차 리비전 PR 완료되었습니다. 🎉 🎉 🎉

**Comment by SQLGate** [comment]
수고 많으셨습니다.
노고에 감사드립니다.

**Comment by preco21** [comment]
Closed https://github.com/electron/electron/pull/7400
